### ISSUE TITLE
Hex release 0.0.4 fails to run

### ISSUE THREAD

**Issue by scrogson** [lpil/dogma#108]
When installing the latest release via `hex` I got the following error:

```
λ mix dogma
** (UndefinedFunctionError) undefined function: Dogma.run/1 (module Dogma is not available)
    Dogma.run({nil, Dogma.Formatter.Simple})
    lib/mix/tasks/dogma.ex:12: Mix.Tasks.Dogma.run/1
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:307: Code.require_file/2
```

Changed to `{:dogma, github: "lpil/dogma", only: :dev}` and it worked.

**Comment by lpil** [comment]
Hello! Thanks for the report.

What was it you changed it from?

**Comment by lpil** [comment]
OK, fixed. I need to work out how to do good integration tests, as my test suite completely failed to pick up this huge problem. Sorry again, and thank you for the report.
