### ISSUE TITLE
Error in Phoenix project

### ISSUE THREAD

**Issue by henrik** [lpil/dogma#112]
Running dogma in a Phoenix project and getting an error:

```
** (EXIT from #PID<0.48.0>) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Dogma.Rule.QuotesInString.check_binary_strings/2
        lib/dogma/rule/quotes_in_string.ex:25: Dogma.Rule.QuotesInString.check_binary_strings(nil, [])
        (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2
        (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:977: Enum.map/2
        lib/dogma/script.ex:88: Dogma.Script.run_tests/2
        lib/dogma/rules.ex:34: Dogma.Rules.test_script/3
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
```

Debugging it a bit, what seems to be going on is this:

* It looks at "_build/test/lib/phoenix/priv/templates/phoenix.gen.html/view.ex" (should it really look inside _build?)
* This is a template file with Elixir syntax errors like `defmodule <%= module %>View do`
* Thus, `script.tokens` is an unhandled `nil` when trying to run a check

Some ideas for improvement:

* Don't look in _build
* Report syntax errors more clearly

**Comment by knewter** [comment]
I actually just came here to leave this exact Issue.  It's like you're in my head @henrik

**Comment by henrik** [comment]
@knewter Yeah, total coincidence, heard about it from some screencast series :)

**Comment by henrik** [comment]
@lpil Thanks for fixing this so quickly! :heart:

**Comment by lpil** [comment]
Did someone mention Dogma in a screencast? That might explain why I've got more visitors the last few days.

No problem @henrik! I feel a bit bad, I keep putting out versions with show stopping bugs. That's `v0.x`, I suppose :shipit:

**Comment by lpil** [comment]
I really dislike how github puts that reference comment in every time you force push.

**Comment by henrik** [comment]
@lpil Yeah, @knewter mentioned it in a recent episode of his http://elixirsips.com/ :)
