### ISSUE TITLE
Why are there functions called probably_X?

### ISSUE THREAD

**Issue by rrrene** [lpil/dogma#117]
Is there a reason why the naming utility functions are named and coded so defensively?

https://github.com/lpil/dogma/blob/91981ea1b2a44b3f3660d88c172f099f507d86bd/lib/dogma/util/name.ex#L15

There might be a good reason for this, but seeing it I'm just thinking "can't we just ensure it's a snake_case name and call it that?"

**Comment by lpil** [comment]
Because it doesn't really check if something is snake case or not, because I don't really know how I'd check that. Probably should make the name more sensible now.

**Comment by rrrene** [comment]
I could refactor this into `snake_case?` and so on, I was just curious if you had any special reasons.

We should be able to check with certainty :wink:

**Comment by lpil** [comment]
Go for it :)

**Comment by rrrene** [comment]
Done. Closing this ticket in favor of the PR.
