### ISSUE TITLE
Formatters fail if Dogma is a dependency

### ISSUE THREAD

**Issue by rrrene** [lpil/dogma#123]
I tried to add Dogma to another project (as a dependency) and get the following when I run the Mix task:

    $ mix dogma --format=json
    ** (UndefinedFunctionError) undefined function: Dogma.Mixfile.project/0 (module Dogma.Mixfile is not available)
        Dogma.Mixfile.project()
        lib/dogma/formatter/json.ex:70: Dogma.Formatter.JSON.metadata/0
        lib/dogma/formatter/json.ex:54: Dogma.Formatter.JSON.finish/1
        lib/dogma/formatter.ex:49: Dogma.Formatter.finish/2
        lib/mix/tasks/dogma.ex:12: Mix.Tasks.Dogma.run/1
        (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2

The problem: `Dogma.Mixfile.project/0` and therefore the `dogma` Mix task is only available within the Dogma project itself. For Dogma to be interoperable within other projects, this should not be the case.

**Comment by lpil** [comment]
Is this just the JSON formatter? It looks like it is, going by the stack trace.
