### ISSUE TITLE
Ideas regarding Runner and Config

### ISSUE THREAD

**Issue by rrrene** [lpil/dogma#129]
I just open sourced the wrapper code I wrote last week and mentioned in a recent PR: https://github.com/rrrene/credo

I tinkered around a bit and tried to use Dogma as a library to implement my own, idiosyncratic rules.

Some observations about what might be applicable to Dogma:

* [Config](https://github.com/rrrene/credo/blob/master/lib/credo/config.ex) - I thought having a Config struct would be really good as opposed to the hardcoded rules. This might not be that interesting to you, since you already settled for the concept of RuleSets - but maybe it would serve the architecture to keep the current ruleset in a Config struct instead of hardcoding it.
* [Dogma.run](https://github.com/rrrene/credo/blob/master/lib/credo.ex#L4) - IMHO the run function is really more handy when it returns `:ok` or a tuple `{:error, [...]}` instead of all processed scripts.
* [Runner](https://github.com/rrrene/credo/blob/master/lib/credo/rule/runner.ex#L9) - The runner is utilizing a `format_callback` instead of a Formatter module. I'm not sure if this is bike-shedding, but I think this step decouples the modules and makes it easier to use individual parts of the software separatly.

All of this is - as always - just an observation on my part. I just thought I'd share the result of two late evenings messing around with Elixir :+1: 

Phuh, that got longer than I thought ... :relieved:  Since this is not even a real "issue" feel free to comment or close!

**Comment by lpil** [comment]
Could you expand on what you think the benefits of the config struct might be? :)

I agree RE Dogma.run. We've not really thought about the return values. I imagine there're a few places we could start returns success tuples, I've just not got into the habit of it yet.

I've been thinking the same RE passing modules names vs passing a function. I blame my head still being stuck in the OO world.

**Comment by rrrene** [comment]
The advantages of using a Config struct - and keep in mind this is just my opinion and I am also infested with the OO virus - is that we (a) can fill this struct with sensible defaults, via the command line option parser or a JSON config. So we ensure that no matter where the Config comes from, there is a single source of truth for it after a certain point in our program.

Secondly we can use pattern matching to accept (a) a config struct and (b) a bare value, which has benefits regarding testability.

Slightly contrived example:

    def find(%Config{files: files}) do
      files.included
      |> Enum.flat_map(&find/1)
      |> exclude(files.excluded)
    end

    def find(path) do
      path
      |> to_glob
      |> Path.wildcard
    end

    def exclude(files, patterns \\ []) do
      Enum.reject(files, &matches?(&1, patterns))
    end

This provides the following advantages: We can unit test `find/1` and `exclude/1` with "bare values", but we can also test the full stack by passing in a Config struct (sort of integration testing, since this is the same struct that is filled via command line options/config file).

I for one really like this design, but as mentioned in the previous comment, this might not necessarily be applicable to Dogma. :+1:

**Comment by alxndr** [comment]
I'm also interested in smoothing out how rulesets can be configured; for now [here's what I came up with](https://github.com/alxndr/flex/blob/1ccbd0ec9cea29f648bc12109265c1b4b7f4d957/lib/dogma_rule_set.ex) for a toy project.

**Comment by lpil** [comment]
See here: https://github.com/lpil/dogma/issues/70

:)
