### ISSUE TITLE
Issues with Latest Version and Custom RuleSets

### ISSUE THREAD

**Issue by jaredklewis** [lpil/dogma#131]
I recently upgraded a project to elixir v.1.1 and subsequently moving dogma to github master since the latest version in Hex is not 1.1 compatible. Since then I have had difficulties running dogma with a custom rule set.

I've created a gist describing the issue here: https://gist.github.com/jaredklewis/7c4f232850474ce794a5

If I remove the config :dogma line from confix.exs, dogma runs fine with the default ruleset. This config line didn't cause me issues in with dogma 0.0.7 and elixir 1.0.

**Comment by lpil** [comment]
Thanks for the report :)

**Comment by meadsteve** [comment]
@jaredklewis glad someone else had this same problem. Thought I'd done something odd. Saw this in my travis build:

https://travis-ci.org/meadsteve/white-bread/builds/82552795

seems to be the same issue.

**Comment by jaredklewis** [comment]
I am very new to Elixir, Mix, and OTP applications, but I noticed the following interesting behavior that may help someone else diagnose the issue.

I added an empty mix task to the project:
```elixir
defmodule Mix.Tasks.MyTask do
  use Mix.Task
  def run(_) do
  end
end
```
After doing so, running the command below successfully lints the project with the custom rule set. 
   
    $ mix do my_task, dogma

However, `mix dogma` still fails as below.

**Comment by ranweiler** [comment]
Hi @jaredklewis! I ran into this issue as well, and though I can't dig into it more right now, I found a smaller variant of your workaround. Executing `mix do run, dogma` also successfully lints using a custom `RuleSet`. Since `mix run` with no args is an effective no-op, you can use `run` in place of your "empty" Mix task, which can be removed.

**Comment by RobinClowers** [comment]
I did some digging, and it looks like the secret sauce to fix this is `Mix.Task.run "loadpaths"` at the beginning of the task.
