### ISSUE TITLE
QuotesInString: exception was raised

### ISSUE THREAD

**Issue by nomicflux** [lpil/dogma#132]
After running `mix dogma`, I received this message:

```
Inspecting 13 files.

...X.XXXXXXX** (EXIT from #PID<0.49.0>) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.byte_size({70, [{:identifier, 70, :inspect}, {:identifier, 70, :app_servers_pids}]})
        (elixir) lib/string.ex:1274: String.do_ends_with/2
        lib/dogma/rule/quotes_in_string.ex:56: Dogma.Rule.QuotesInString.invalid?/1
        lib/dogma/rule/quotes_in_string.ex:30: Dogma.Rule.QuotesInString.check_binary_strings/2
        (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2
        (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:977: Enum.map/2
        lib/dogma/script.ex:96: Dogma.Script.run_tests/2
```

I'm not really sure in what file of mine it's choking.  Everything in my application complies and runs correctly, so this seems to be a dogma-specific issue.  I have it included in my `mix.exs` dependencies as `{:dogma, "~> 0.0", only: :dev}`.  

(Sorry if I'm leaving out any important information - just getting started filling out bug reports here on github)

Edit: the above exception is from Elixir v1.0.5

**Comment by lpil** [comment]
Hey! Thanks for the report. Is your application open source? If so, may we see it so we can replicate the error?

Thanks.

**Comment by nomicflux** [comment]
Unfortunately, it is not open source.

But I do have a little more info: the above error was from Elixir v1.0.5.  I just updated to v.1.1.0 - still got pretty much the same message, but I have updated line numbers: 

```
Inspecting 13 files.

....XXXXXXX** (EXIT from #PID<0.47.0>) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.byte_size({{70, 12, 39}, [{:identifier, {70, 14, 21}, :inspect}, {:identifier, {70, 22, 38}, :app_servers_pids}]})
        (elixir) lib/string.ex:1333: String.do_ends_with/2
        lib/dogma/rule/quotes_in_string.ex:56: Dogma.Rule.QuotesInString.invalid?/1
        lib/dogma/rule/quotes_in_string.ex:30: Dogma.Rule.QuotesInString.check_binary_strings/2
        (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
        (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:1043: Enum.map/2
        lib/dogma/script.ex:96: Dogma.Script.run_tests/2

17:19:05.519 [error] Task #PID<0.567.0> started from #PID<0.47.0> terminating
** (ArgumentError) argument error
    :erlang.byte_size({{70, 12, 39}, [{:identifier, {70, 14, 21}, :inspect}, {:identifier, {70, 22, 38}, :app_servers_pids}]})
    (elixir) lib/string.ex:1333: String.do_ends_with/2
    lib/dogma/rule/quotes_in_string.ex:56: Dogma.Rule.QuotesInString.invalid?/1
    lib/dogma/rule/quotes_in_string.ex:30: Dogma.Rule.QuotesInString.check_binary_strings/2
    (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:1043: Enum.map/2
    lib/dogma/script.ex:96: Dogma.Script.run_tests/2
Function: #Function<1.45248647/0 in Dogma.Rules.test/2>
    Args: []
```

**Comment by lpil** [comment]
Could you possibly recreate it in a simple version?

I've really got to work out how to get the name of the file being linted in those stack traces.

**Comment by nomicflux** [comment]
Found the offending code.  The original lines were:

```
        Applist.note :red,
          "Killing #{inspect app} at #{inspect app_pid}, " <>
          "#{inspect app_servers_pids}"
```

I changed it to:

```
        Applist.note :red,
          "Killing #{inspect app} at #{inspect app_pid}, " <>
          inspect app_servers_pids
```

And everything worked fine.

**Comment by lpil** [comment]
Huh. There's clearly a bug here. I'll try and reproduce this when I have time. Thanks!

**Comment by rrrene** [comment]
The problem is that the `invalid?` function assumed it was getting a binary, but on interpolation it gets a regular ast tuple, which in this case justifies simply returning `false`.

**Comment by meadsteve** [comment]
Just a thought on this. Is it good style to have a string consisting only of interpolation or is there a clearer way to show intent. Do we/should we have a rule to cover this?

**Comment by lpil** [comment]
If we think it's something someone might want to avoid, we should make a rule for it.

Could you open an issue please?

**Comment by nomicflux** [comment]
Great - I was logging in to suggest making a rule for that, especially because it happened due to trying to meet the rules for line length (along with some carelessness on my part).
