### ISSUE TITLE
(ArgumentError) argument error, :erlang.byte_size

### ISSUE THREAD

**Issue by alxndr** [lpil/dogma#135]
I'm trying to add dogma to [a pet project of mine](https://github.com/alxndr/flex/tree/style-tweaks) but finding that upgrading to 0.0.8 results in this error:

```
$ mix dogma
Inspecting 9 files.

....X.** (EXIT from #PID<0.49.0>) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.byte_size({43, [{:at_op, 43, :@}, {:bracket_identifier, 43, :mp3_options}, {:"[", 43}, {:atom, 43, :bitrate}, {:"]", 43}]})
        (elixir) lib/string.ex:1274: String.do_ends_with/2
        lib/dogma/rule/quotes_in_string.ex:56: Dogma.Rule.QuotesInString.invalid?/1
        lib/dogma/rule/quotes_in_string.ex:30: Dogma.Rule.QuotesInString.check_binary_strings/2
        (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2
        (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
        (elixir) lib/enum.ex:977: Enum.map/2
        lib/dogma/script.ex:96: Dogma.Script.run_tests/2
```

Seems like it's complaining about [this line](https://github.com/alxndr/flex/blob/9b5388270ba6886cd49d2d3f2b6820ecf597f61d/lib/flex.worker.ex#L43)? How should I go about fixing this?

**Comment by lpil** [comment]
Heya! This is already fixed on master.

https://github.com/lpil/dogma/issues/132
https://github.com/lpil/dogma/pull/133

Thanks for the report :)

**Comment by alxndr** [comment]
Thanks! Is it just in master and not 0.0.8?

**Comment by lpil** [comment]
Yup. Tell you what, I'll release a new version. Give me a few minutes.

**Comment by alxndr** [comment]
:tada: :confetti_ball:

**Comment by lpil** [comment]
There you go :)

**Comment by alxndr** [comment]
Fixed! Thanks so much. (Now to investigate custom rule sets...)

**Comment by lpil** [comment]
Have fun!

If you make any cool rules, maybe make a pull request. We certainly need more.

**Comment by alxndr** [comment]
Shall do!

**Comment by alxndr** [comment]
No cool rules yet, but I was looking at how to tweak the existing rule sets and found it to be pretty awkward-feeling. [Here's what I came up with](https://github.com/alxndr/flex/blob/7ee05d2/lib/dogma_rule_set.ex#L4-L8)...

**Comment by lpil** [comment]
There will be a more convenient way of configuring dogma, but I've not got round to writing it yet I'm afraid.

**Comment by alxndr** [comment]
Gotcha

**Comment by alxndr** [comment]
[First whack at a new rule](https://github.com/alxndr/dogma/blob/e7a2f34cf70701859b3c730cb3a6637c9bfdf770/lib/dogma/rule/variable_name_length.ex), using `VariableName` as a starting point. Any advice? (My first time messing with Elikir ASTs...)

**Comment by lpil** [comment]
Seemed complex at first, but now I look it's because it checks variables inside destructuring assignments. Probably as complex as it needs to be. :)
