### ISSUE TITLE
Dogma error under CI: no function clause matching in Dogma.Rule.FinalCondition.find_last_cond/1

### ISSUE THREAD

**Issue by thewalkingtoast** [lpil/dogma#148]
Running `mix dogma` locally works great, but when ran under Circle CI we're getting this error:

![screen shot 2015-10-28 at 7 23 12 am](https://cloud.githubusercontent.com/assets/864643/10791385/76b674dc-7d45-11e5-95d0-6d0cf466443a.png)

Here is our CI env:
![screen shot 2015-10-28 at 7 23 42 am](https://cloud.githubusercontent.com/assets/864643/10791400/8aa49be0-7d45-11e5-969b-14ad8d3c8da9.png)

Here is the relevant part of our `mix.exs` file:

![screen shot 2015-10-28 at 7 24 05 am](https://cloud.githubusercontent.com/assets/864643/10791424/a56ab8e2-7d45-11e5-8620-91275ce785b5.png)

**Comment by lpil** [comment]
It's failing here -> https://github.com/lpil/dogma/blob/fb10e5eeb5dbadd966fa6e83bb5e0e54ddf50e1d/lib/dogma/rule/final_condition.ex#L77

Is your project open source? If so, you link me it for debugging? Or alternatively could you provide a minimal failing example?

I think it's failing on line 1490 a file. We really need a way to make stack traces provide more useful information.

**Comment by thewalkingtoast** [comment]
@lpil It is not open source unfortunately. I will work on getting a reproducible project for you. Thank you for the quick reply!

**Comment by thewalkingtoast** [comment]
@lpil 
I have a reproduction. It works great locally but not under CircleCI. If you're not using CircleCI, they have a small free plan. Maybe something isn't quite right in the [setup file](https://github.com/thewalkingtoast/hawk/blob/master/circle.yml)?

https://github.com/thewalkingtoast/hawk
https://circleci.com/gh/thewalkingtoast/hawk/3

**Comment by lpil** [comment]
Thanks Adam. I'll resolve this as soon as I find time, but I'm not sure when that might be. In the mean time you could ignore the file in question for now maybe?

```elixir
config :dogma,
  exclude: [
    ~r(\Asome/path/here),
  ]
```

**Comment by thewalkingtoast** [comment]
@lpil Thanks for taking the time to look at this! I appreciate it. :)

I can't tell from the error output what file to exclude. This is a new, bare-bones Phoenix app with no new custom files. Or do you mean the file inside dogma generating the error? (i.e., this file: https://github.com/lpil/dogma/blob/fb10e5eeb5dbadd966fa6e83bb5e0e54ddf50e1d/lib/dogma/rule/final_condition.ex)

```elixir
config :dogma,
  exclude: [
    ~r(\Alib/dogma/rule/final_condition.ex),
  ]
```

**Comment by lpil** [comment]
Nope, it is the file in which the error is contained. Which one that is we don't know... I have a sneaky feeling it's going to be some vendor folder on CircleCI...

How about we disable that rule for now? I've just released a new version that should let you do this:

```elixir
config :dogma,
  override: %{
    FinalCondition => false,
  }
```

**Comment by thewalkingtoast** [comment]
@lpil Thanks, I will try that. Your comment about a vendor folder on CircleCI gave me an idea. I will try it and report back.

**Comment by thewalkingtoast** [comment]
@lpil The vendor folder idea was it. The circle.yml checked out the elixir source into the repo folder so dogma was running through that as well. Moving it out let it pass so this was user error. Thanks for your assistance and quick responses!

https://circleci.com/gh/thewalkingtoast/hawk/9

**Comment by lpil** [comment]
Marvellous!

I'm gunna reopen this as I want to make it handle whatever whatever code it was failing on. :)

**Comment by lpil** [comment]
Turns out if you define a macro called "cond" weird things will happen.
