### ISSUE TITLE
Ordering of module attributes, alias, @moduledoc, @behaviour

### ISSUE THREAD

**Issue by mgartner** [lpil/dogma#161]
Is there any consensus on how module attributes, aliases, `@moduledocs`, `@behaviour`, etc. should be ordered or grouped at the beginning of a module. Is this something there should be a rule around?

**Comment by lpil** [comment]
This sounds like something we want, though I do not know the exact order.

We could create a function that returns the order in which each of these appear in a given module. This would be a good starting point for this rule, and the exact order can be configured and checked easily once we have this.

**Comment by meadsteve** [comment]
:+1: idea. In the elixir-lang repo ```@moduledocs``` is normally the first thing so that seems a good starting point.

**Comment by mgartner** [comment]
I'll work on going through some of the more popular elixir projects and seeing if there are any common trends. It probably makes sense to make this ordering customizable too.

**Comment by lpil** [comment]
I think I generally go for something like this:

```
@moduledoc
@behaviour
use
@alias
@require
@import
```
