### ISSUE TITLE
InterpolationOnlyString fails for utf8 type

### ISSUE THREAD

**Issue by aaronjensen** [lpil/dogma#164]
```elixir
  defp downcase_first_letter(<<first_letter :: utf8>> <> rest) do
    String.downcase(<<first_letter>>) <> rest
  end
```

The first line fails, thinking it is an interpolation, which it is not.

**Comment by lpil** [comment]
Thanks!

**Comment by KronicDeth** [comment]
Similar thing happened to me for 

```
@spec monitor_channel({:stop, << _ :: 264 >>}) :: {:stop, << _ :: 264 >>}
defp monitor_channel(return = {:stop, _}), do: return
```

But it's the type that makes dialyzer happy (as opposed to just using `String.t`, which dialyzer says is a supertype).    Mine might be solvable by noticing you're in an `@spec` and so it's a type signature, which would be different than fixing it for @aaronjensen.

**Comment by mgartner** [comment]
I believe this was fixed by: https://github.com/lpil/dogma/commit/2873ad14817349a7c12f2516b2a58d549cc32df5

**Comment by KronicDeth** [comment]
I was able to re-enable the rule while on dogma `0.1.5`, so fixed me for the `@spec` usage.

**Comment by lpil** [comment]
Thanks. I need a better way of keeping track of these issues :)
