### ISSUE TITLE
What if rules were structs?

### ISSUE THREAD

**Issue by lpil** [lpil/dogma#171]
The way in which we currently pass around the names of Rule modules seems kind of awkward to me, I wonder if we can do better. What if rules were structs?

```elixir
defmodule Dogma.Rule.LineLength do
  defstruct enabled: true,
            max_length: 80
end

defimpl Rule, for: Dogma.Rule.LineLength do
  @alias Dogma.Rule.LineLength
  @alias Dogma.Script

  def test(rule, %Script{} = script) do
    # perform the test
  end
end
```

The we just iterate over the list of rule structs and call the `Rule.test/2` function on each one.

We could write a `defrule` macro to cut down on the boilerplate.

```elixir
defrule LineLength, [max_length: 80] do
  def test(rule, %Script{} = script) do
    # perform test
  end
end
```

This would also solve the problem of having to either have very verbose names in the mix config, or concatenating `Dogma.Rule` on the start of every name atom.

**Comment by meadsteve** [comment]
I like this. The struct gives a really clear structure for what config options are available. It even makes it technically possible for IDEs to autocomplete on this. 

I'm not sure if this does solve the ```very verbose names in the mix config, or concatenating Dogma.Rule on the start of every name atom.``` problem however. The struct will still have the verbose name right?

**Comment by meadsteve** [comment]
Also just realised it means you can do things like
```elixir
rule_structs
  |> Enum.filter(fn rule -> rule.enabled end)
```
to get all the enabled rules. Seems a sensible way of doing this.

**Comment by lpil** [comment]
Well, you can alias the patent module, that helps a little, and is much clearer than the previous solution.

Would be good to get a review in the PR once I've made some progress. :)

**Comment by meadsteve** [comment]
@lpil no problem. Let me know when you'd like me to take a look (random unavailability due to travelling around over xmas caveat applies though).

**Comment by lpil** [comment]
Merry everybody :santa:
