### ISSUE TITLE
mix dogma crashes when a rule is overridden

### ISSUE THREAD

**Issue by michalwarda** [lpil/dogma#182]
For some odd reason when I try to specify a rule in the override section of dogma config I get an error when trying to run `mix dogma`
```
mix dogma
** (Mix.Config.LoadError) could not load config config/config.exs
    ** (CompileError) config/config.exs:36: Dogma.Rule.ModuleDoc.__struct__/0 is undefined, cannot expand struct Dogma.Rule.ModuleDoc
    (elixir) src/elixir_map.erl:58: :elixir_map.translate_struct/4
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
```
Here's a link to the project on correct branch: [https://github.com/elpassion/el-mascarar/tree/add_dogma](https://github.com/elpassion/el-mascarar/tree/add_dogma)
And here is the link to the config file itself: 
[https://github.com/elpassion/el-mascarar/blob/add_dogma/config/config.exs](https://github.com/elpassion/el-mascarar/blob/add_dogma/config/config.exs)

**Comment by lpil** [comment]
It seems you're using the new configuration format that's on the master branch. This has not yet been released. Perhaps update your mix config to make use of the master branch :)

```elixir
{:dogma, "~> 0.0", github: "lpil/dogma", only: :dev}
```

**Comment by bryansray** [comment]
Is version 0.0.11 using the new configuration format on the master branch?

**Comment by bryansray** [comment]
Using 0.0.11 when I attempt to do this:

`config :dogma, override: [ %Rule.LineLength { max_length: 120 } ]`

And receive this error message when running `mix dogma`:

```
** (CompileError) config/config.exs:36: Dogma.Rule.LineLength.__struct__/0 is undefined, cannot expand struct Dogma.Rule.LineLength
(elixir) src/elixir_map.erl:58: :elixir_map.translate_struct/4
(stdlib) lists.erl:1353: :lists.mapfoldl/3
(stdlib) lists.erl:1354: :lists.mapfoldl/3
```

**Comment by lpil** [comment]
I've just published a new version with the changes :)
