### ISSUE TITLE
Dogma override config throwing "cannot expand struct" error

### ISSUE THREAD

**Issue by elliotlarson** [lpil/dogma#183]
I'm using Dogma `0.1.0`.  I've added the configuration from the documentation to my `config/config.exs` file:

```elixir
alias Dogma.Rule

config :dogma,

  # Select a set of rules as a base
  rule_set: Dogma.RuleSet.All,

  # Pick paths not to lint
  exclude: [
    ~r(\Alib/vendor/),
  ],

  # Override an existing rule configuration
  override: [
    %Rule.LineLength{ max_length: 120 },
    %Rule.HardTabs{ enabled: false },
  ]
```

When I run:

```bash
$ mix dogma
```

... I get the following error:

> ** (Mix.Config.LoadError) could not load config config/config.exs
    ** (CompileError) config/config.exs:45: Dogma.Rule.LineLength.__struct__/0 is undefined, cannot expand struct Dogma.Rule.LineLength
      (elixir) src/elixir_map.erl:58: :elixir_map.translate_struct/4
      (stdlib) lists.erl:1353: :lists.mapfoldl/3
      (stdlib) lists.erl:1354: :lists.mapfoldl/3

**Comment by lpil** [comment]
Hey. Thanks for the report. Is this project open source, so I can take a look?

**Comment by elliotlarson** [comment]
Sure.  It's just a faux blog learning Elixir/Phoenix project.  Here's the url: https://bitbucket.org/onehouse/blog_phoenix/overview

**Comment by lpil** [comment]
Thank you, I'll take a look when I can.

**Comment by lpil** [comment]
Fixed by @neerfri :D

**Comment by lpil** [comment]
Thanks @elliotlarson

**Comment by aaronjensen** [comment]
fwiw, this did not fix it for us:

```
$ mix dogma
** (Mix.Config.LoadError) could not load config config/dogma.exs
    ** (CompileError) config/dogma.exs:13: Dogma.Rule.LineLength.__struct__/0 is undefined, cannot expand struct Dogma.Rule.LineLength
    (elixir) src/elixir_map.erl:58: :elixir_map.translate_struct/4
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
```

**Comment by aaronjensen** [comment]
(we are on 0.1.2)
