### ISSUE TITLE
clarification regarding PipelineStart

### ISSUE THREAD

**Issue by neerfri** [lpil/dogma#191]
@lpil  can you please explain the rational behind [PipelineStart](https://github.com/lpil/dogma/blob/master/docs/rules.md#pipelinestart)?

What's wrong with:
```elixir
Regex.run(~r/my-match$/m, match_text)
|> List.last
```
or:
```elixir
  test "MyPlug works" do
    conn = conn(:get, "/")
    |> MyPlug.call([])

    assert conn.status == 200
  end
```
Is there a better way to write those?

**Comment by lpil** [comment]
It's for the sake of consistency.

**Comment by neerfri** [comment]
So how would you suggest to write the examples above?

This code seems a bit funny, no? (since `:get` is not the point here, `conn` is):
```elixir
conn = :get
|> conn("/")
|> MyPlug.call([])
```

**Comment by lpil** [comment]
Yup, that's how I write it.

**Comment by neerfri** [comment]
OK, thanks!
