### ISSUE TITLE
Dogma.Rule.TakenName warns when String.Chars is implemented.

### ISSUE THREAD

**Issue by Gyllsdorff** [lpil/dogma#201]
``` elixir
# File: lib/foo/bar.ex
defmodule Foo.Bar do
  defstruct foo: "foo", bar: "bar"
end

defimpl String.Chars, for: Foo.Bar do
  def to_string(foo_bar), do: "#{foo.foo} -- #{foo.bar}"
end
```

```
== lib/foo/bar.ex ==
6: TakenName: `to_string` is already taken and overrides standard library
```

Unless I am doing something wrong this means we can't provide implementations of String.Chars without Dogma complaining.

One solution is to make the reserved words list in `lib/dogma/rule/taken_name.ex` configurable so we can remove `to_string` from the list.

**Comment by lpil** [comment]
This is certainly a bug, thank you for the report.

**Comment by lpil** [comment]
Perhaps we should not check inside `defimpl`. What do you think?

**Comment by lpil** [comment]
Thoughts @meadsteve ?

**Comment by meadsteve** [comment]
I'm wondering about the suggestion to remove ```to_string``` from the list. I'm not sure I see the benefit of having a rule that spots usages of this. I would have thought the elixir compiler would provide a sensible/warning error when this was an issue.

Ignoring the rule when inside ```defimpl``` means you'd miss any of the others inside that same impl meaning the rule would be missing some of the things it's intended to catch anyway. 

Maybe it's worth thinking removing this rule altogether? What problem is it intended to solve?

**Comment by lpil** [comment]
Current thinking- only check private functions as public ones will be generally referred to using a qualified name.

**Comment by AndrewDryga** [comment]
The same issue occurs with different defimp in this code: https://github.com/ericmj/mongodb/blob/master/lib/bson/types.ex#L13

**Comment by StevenXL** [comment]
Not sure how I can contribute to this issue, but I am getting the same problem. 

Here's a [gist](https://gist.github.com/StevenXL/7e6322bd34bc0783b3327ce6a95e23ff) of what happens when I try to run dogma on my code.

Is this even the same problem? Seems very odd to get errors from modules defined in the elixir standard library.

**Comment by lpil** [comment]
That's a different issue, a crash caused by trying to convert an `unquote` expression to a string. It's a different bug for sure. Could you open another issue please @StevenXL ?

**Comment by StevenXL** [comment]
@lpil thank you for the response. I have opened a new issue #227.
