### ISSUE TITLE
LiteralInCondition: Literal value found in conditional in case statement

### ISSUE THREAD

**Issue by ankithherle** [lpil/dogma#204]
```
case { weather, weekday } do
  { :raining, :weekend } ->
    IO.puts "I'm will eat 2 apples!"

  { :raining, _ } ->
    IO.puts "I'm eating apple"

  { :sunny, _ } ->
    IO.puts "I'm happy!"

  { _, :sunday } ->
    IO.puts "I'm eating rice"

  { _, _ } ->
    IO.puts "I don't know what I'll eat"
end
```

Above code gives `LiteralInCondition: Literal value found in conditional` error. This is may be because `dogma` thinks `{ weather, weekday }` as Literal, but it has values inside. I think its an issue with `dogma`

Reference: http://stackoverflow.com/a/21079882

**Comment by lpil** [comment]
Thanks for the report :)
