### ISSUE TITLE
"Useless" string interpolation detected in a Regex sigil

### ISSUE THREAD

**Issue by somlor** [lpil/dogma#209]
String interpolation in a regex sigil is useful. 😄 
```
foo = "hello"
bar = "whatever"
foo =~ ~r/#{bar}/
```
`InterpolationOnlyString: Useless string interpolation detected.`

**Comment by lpil** [comment]
I see how that could be useful. Might I suggest `Regex.compile/2` for now? It has better error handling too.

**Comment by somlor** [comment]
@lpil thanks. And yep, `Regex.compile/2` is what I'm using for now.
