### ISSUE TITLE
Configuration and ignoring via comments

### ISSUE THREAD

**Issue by sobolevn** [lpil/dogma#219]
I have seen, that `dogma` has a mechanism to extract all comments from a source files: https://hexdocs.pm/dogma/Dogma.Util.Comment.html

The question is, how do we suppose to use it? I could not find any docs about it.

The way I used to do it (coming from `pylint`, `eslint` and `shellcheck`):
1. Configuration for all file in the header
2. Configuration for a single line as an inline comment (because sometimes you have to break the rules)

Thanks!

**Comment by lpil** [comment]
I'd like the inline comment feature :)

**Comment by scouten** [comment]
+1!
