### ISSUE TITLE
Nested string interpolation incorrectly treated as comment

### ISSUE THREAD

**Issue by mbuhot** [lpil/dogma#224]
This following code which does not contain a comment, produces a CommentFormat warning:

``` Elixir
    conn = conn
      |> put_req_header("authorization", "Basic #{Base.encode64("#{@username}:#{@password}")}")
```

``` bash
33: CommentFormat: Comments should start with a single space
```

Separate to the issue of weather nested string interpolation is a good idea or not, dogma should not output a `CommentFormat` warning for this code.

**Comment by lpil** [comment]
Good find. Thank you.

**Comment by lpil** [comment]
This is proving quite hard to fix in a non-hacky fashion. The preprocessor that removes strings from source code needs to be taught how to handle string interpolation, which can be infinitely nested. It'll need to have some understanding of how deeply nested it is, which is non-trivial.

Another interesting question is whether stripping strings would keep the code contents of interpolation somehow. This seems more correct, but would not fix this issue.

Perhaps as a hacky fix we could tell this rule to ignore "comments" that look like this -> `#{`.

**Comment by mbuhot** [comment]
@lpil ignoring the `#{` "comments" would certainly suppress this warning, nice hack!

More broadly, Dogma already has opinions on correct usage of string interpolations: `Rule.InterpolationOnlyString`, `Rule.LiteralInInterpolation`.
Maybe since nested interpolation is rarely used, dogma should have a rule to disallow it?

This would still require the preprocessor be able to detect the nesting, but I assume that is a simpler problem than the infinitely nested code preserving case.

A quick google found the coffeescript linter uses this rule: [no_nested_string_interpolation.coffee](https://github.com/clutchski/coffeelint/blob/master/src/rules/no_nested_string_interpolation.coffee)

**Comment by jeffrom** [comment]
Here's another example that causes this:

```elixir
def make_pid(s) when is_binary(s), do: :erlang.list_to_pid('<#{s}>')
```
