### ISSUE TITLE
Function Pipe Chains must start with a bare value ... but how?

### ISSUE THREAD

**Issue by scouten** [lpil/dogma#225]
Dogma is giving me an error on the following line ...

```elixir
    conn = build_conn() |> get("/confirm?" <> @valid_link)
```

... but I have no idea how to convert that empty value to a bare value.

Is that even possible? If so, Dogma should suggest how to do it. If not, the error should be retracted.

**Comment by lpil** [comment]
This is a bug. Dogma things that `build_conn()` has arguments!

Would you like to have a go at fixing this? :)

**Comment by scouten** [comment]
OK 😄
