### ISSUE TITLE
Rule: Sigil Delimiters 

### ISSUE THREAD

**Issue by lpil** [lpil/dogma#23]
We should pick a delimiter for sigils and stick to it unless the sigil contains that delimiter.

It feels like regexs should use `/`.

**Comment by jacknoble** [comment]
Some thoughts: Regexs should use `/` unless they contain that a `/` character in which case they should use `{` and `}`. This matches the "what would be lease surprising to someone coming from Ruby" rule-of-thumb. Feels to me like the others should always use `(` and `)`. 

Also seems like there should be separate rules for each sigil (at minimum a separate rule for regexs) so they can be easily customized.
