### ISSUE TITLE
Comment rules should ignore shebang line in scripts

### ISSUE THREAD

**Issue by cgiffard** [lpil/dogma#231]
Unfortunately, including a space after the comment renders the standard shebang line inoperable:

``` bash
#!/usr/bin/env elixir 
```

I wonder if dogma should know to ignore the first comment line if it matches the `#!` pattern.

**Comment by lpil** [comment]
Sounds good. Want to make a PR?

**Comment by cgiffard** [comment]
I'll look into it tomorrow! (Still relatively new to Elixir — so fair warning!) :)

**Comment by lpil** [comment]
Here's a good place to look: https://github.com/lpil/dogma/blob/master/lib/dogma/rule/comment_format.ex#L29

Be sure to add a unit test!
