### ISSUE TITLE
Incorrect rule match in SpaceAfterComma

### ISSUE THREAD

**Issue by techgaun** [lpil/dogma#235]
Seems like the root cause is how `Dogma.Util.ScriptStrings` strips the string literal contents and it seems to affect `SpaceAfterComma`. If there's a code with comment that contains single double-quote, it seems to create this issue.

Below is the sample code-block that can produce this behavior:

```
# "
IO.puts ","
```

**Comment by lpil** [comment]
Thanks :)

`Dogma.Util.ScriptStrings` needs to be re-written to be honest, there's a ton of edge cases it doesn't handle correctly.
