### ISSUE TITLE
Implementing the Inspect protocol causes a TakenName error

### ISSUE THREAD

**Issue by rhruiz** [lpil/dogma#241]
Hello,

implementing the `Inspect` protocol for a module causes a

`TakenName: `inspect` is already taken and overrides standard library`

and I should not feel ashamed of that.

Here is a sample code that triggers the complaint:

```
defmodule MyModule do
  defstruct :param
end

defimpl Inspect, for: MyModule do
  def inspect(_, _), do: "<my module inspection here>"
end
```

**Comment by lpil** [comment]
Some existing discussion over in https://github.com/lpil/dogma/issues/201

**Comment by lpil** [comment]
I think I might just remove this rule. Thoughts?

**Comment by rhruiz** [comment]
I will close this one, let's keep that in #201 

Search did not find the defimpl I searching for before opening this one.
