### ISSUE TITLE
Phoenix clean install 143 files, 835 errors

### ISSUE THREAD

**Issue by pmelnichuk** [lpil/dogma#248]
disclaimer: I'm an elixir noob. New to the elixir community but trying to maintain a clean repo from the start.

Looks like phoenix from the base install fails miserably. is this normal?

Generated dogma app
Inspecting 143 files.

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX...XXX.X...X.XXX...X....X..X...XX.XXX.X.X.XXXXX.X.XXXXXX.XXX.X.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

143 files, 835 errors!

**Comment by lpil** [comment]
Phoenix doesn't adhere to the style specified by Dogma, however that does seem like a lot of files. Is it checking your deps, perhaps?

**Comment by rhnonose** [comment]
It's suddenly checking inside `assets` folder (I recall not checking before, not sure).

**Comment by lpil** [comment]
We have always checked any director called `assets` https://github.com/lpil/dogma/blob/426845e14cdb11a06561702c0a0fd61578205f6e/lib/dogma/script_sources.ex#L9

The difference now is likely that Phoenix 1.3 creates a directory called `assets` with NPM deps in it.

I would welcome a pull request that made Dogma ignore the `node_modules` directory.
