### ISSUE TITLE
Optionally auto fix violations where possible + safe

### ISSUE THREAD

**Issue by errm** [lpil/dogma#25]
Rewrite to correct the failing rules where possible. As in go fmt or rubocop -a

**Comment by lpil** [comment]
Certainly needed. Sounds hard.

**Comment by lpil** [comment]
Does anyone have any ideas as to how we might do this? Sounds difficult. Maybe we should look into how Rubocop does it.

**Comment by meadsteve** [comment]
What rules do we currently have that we'd want to consider doing this on? The ones that comes to mind at the moment are the WindowsLineEnding and TrailingWhiteSpace.

**Comment by lpil** [comment]
They sound like easy wins, and I think we might be able to manage some others, but I don't really know what's the best way to architect this bit of the system.

**Comment by meadsteve** [comment]
First thoughts would be. Have a Fixable behaviour then do the following:

1. Run all tests.
2. Prompt if any of the errors are fixable.
3. Apply fixes.
4 Rerun tests that are fixable and output updated number of violations.

For simple rules like the ones I mentioned the fixing could be as simple as running a map over each source line. It'd definitely be harder for rules that make use of the ast.

**Comment by lpil** [comment]
I mean internally, rather than from the user interaction point of view. Will give it some thought.

**Comment by meadsteve** [comment]
Internally I'd be tempted to handle this with a function that takes all the lines of a script and returns all the lines of the "fixed" file. I think this would work for all the simple ones which I think would be the only ones we'd want  to automatically fix.

**Comment by lpil** [comment]
I don't want to re-run the test correction loop as it's possible to get into an infinite loop here.

**Comment by meadsteve** [comment]
agreed. I don't seen any reason why you'd run any fixing steps a 2nd time. If any errors remain after automatic fixes then it's probably something that can't be fixed automatically.
