### ISSUE TITLE
Rule: Cyclomatic complexity

### ISSUE THREAD

**Issue by lpil** [lpil/dogma#30]
?

**Comment by meadsteve** [comment]
Things like npath and cyclomatic complexity might be worth breaking out as a separate tool.
I think it's worth keeping dogma focussed as a code style/formatting/ tool.

**Comment by lpil** [comment]
I like these metrics in Rubocop, as they're basically a proxy for "don't write huge methods". The alternative is number of lines, which I detest, as it discourages you from splitting long lines for legibility.

**Comment by meadsteve** [comment]
yeah I don't disagree with them being useful (definitely much prefer it over line length).

But for me it fits in to a different logical category. These kind of checks give you feedback on how you design/architecture your software. Where as all the current rules are about how you lay it out and format it.

**Comment by lpil** [comment]
This is why we need #5 before this I think. In my experience of linters in a professional environment these are the ones that cause the most friction.

**Comment by meadsteve** [comment]
Good point about #5 . I'd definitely be happier with this if I could run dogma twice. Once with formatting and once with design/code quality checks.

**Comment by lpil** [comment]
Perhaps by specifying a config file with a runtime flag?

**Comment by meadsteve** [comment]
so something like?
```bash
mix dogma --config code_style.exs
mix dogma --config code_quality.exs
```

**Comment by lpil** [comment]
Open an issue if you want it :)

**Comment by meadsteve** [comment]
Done! #38 Issue all the things!

**Comment by rrrene** [comment]
Most linting tools have some notion of "severity level", where "style/convention" means things from a style guide and "warning" means "look out how you write your code" (what @meadsteve said about "architecture).

Maybe rules could be tagged with this "severity", so you can do things like exit with an exit code different from 0 if "only" style violations occur, but with a "breaking" exit code when more severe things fail.

Just my two cents :grinning: great project!

**Comment by lpil** [comment]
If you want a feature, open an issue please :)

Thanks for the complement, you've got some cool stuff too!
