### ISSUE TITLE
Integration or contract tests

### ISSUE THREAD

**Issue by lpil** [lpil/dogma#34]
Hell, why not?

**Comment by meadsteve** [comment]
I wonder what benefit we'd get from the integration tests. We've got the pieces covered by unit tests and as the project is dog fooding itself we at least know that it runs.

**Comment by lpil** [comment]
I want something that verifies everything is hooked up correctly, as unit tests fail to capture this, and I *will* break this when I refactor things like the `Dogma` module. Luckily [this](https://github.com/lpil/dogma/blob/master/.travis.yml#L19) kind of works like an integration test on CI.

I think once I'm done with #73 I could achieve this security I want using contract tests.
