### ISSUE TITLE
Allow configuration to be specified in runtime flag

### ISSUE THREAD

**Issue by meadsteve** [lpil/dogma#38]
This requires #5 to be implemented first. Being able to do something like the following would be useful:

```bash
mix dogma --config code_style.exs
mix dogma --config code_quality.exs
```

**Comment by meadsteve** [comment]
I believe this will mostly be handled by PR #42. Although I went with passing in a Module containing the rules rather than a file.

That said I've used the approach of having a .exs file containing a config in a project of mine(https://github.com/meadsteve/white-bread/) so it could still be an option.

**Comment by lpil** [comment]
Can you link the files that handle the loading of the config please? :)

**Comment by meadsteve** [comment]
https://github.com/meadsteve/white-bread/blob/master/lib/mix/tasks/white_bread.run.ex#L18

Basically loads the exs file and gets the first module defined in it.

**Comment by lpil** [comment]
Done by Steve a while back. I'm likely going to break this at some point though.
