### ISSUE TITLE
Enable users to add custom rules

### ISSUE THREAD

**Issue by lpil** [lpil/dogma#41]

**Comment by meadsteve** [comment]
@lpil it feels like with the sets congif work you did (8f6eee3) we already have this. Shall we close?

**Comment by lpil** [comment]
We can have a custom ruleset that adds additional rules, but I want to also be able to add these though he additional configuration section. It also needs to be tested, as I'm not sure I've done this well.

**Comment by lpil** [comment]
Now possible with `override` in the mix config.
