### ISSUE TITLE
Rule: Function name

### ISSUE THREAD

**Issue by lpil** [lpil/dogma#49]
Function names must be snake_case

**Comment by meadsteve** [comment]
@lpil happy to implement this unless you've already started?

**Comment by lpil** [comment]
Go for it :)

These might be handy

https://github.com/lpil/dogma/blob/master/lib/dogma/util/name.ex
https://github.com/lpil/dogma/blob/master/lib/dogma/rules/variable_name.ex

**Comment by meadsteve** [comment]
ah. Well that makes it fairly trivial :smile:
