### ISSUE TITLE
Make rules configurable

### ISSUE THREAD

**Issue by lpil** [lpil/dogma#5]

**Comment by lpil** [comment]
Suggestion from @Joe-noh 

> I think following design is simple, least astonishment.
> 
> - `dogma` is installed as project deps (`only: :dev`).
>   - don't need to install globally.
> - global setting file is `~/.dogma.exs`.
>   - It is pretty good if initializing task like `mix dogma.global.init` is provided.
> - `config/confg.exs` imports global setting file at first
>   - Configuration which comes after the `import`, local project configuration, overwrites global one.
> 
> > there's no obvious way of installing hex packages globally.
> 
> Just so you know, it is not impossible. Phoenix does with `mix archive.install`. http://www.phoenixframework.org/v0.13.1/docs/installation.

**Comment by meadsteve** [comment]
I like the idea of mix.exs like file. So if a project contains a dogma.exs then those rules are loaded. If not we default to loading a file packaged with dogma (hopefully most people would use this as competing standards confuse things). This would allow anyone contributing to the repo to see what the formatting rules are. For a config format what about:

```elixir
defmodule Dogma.Config do
  def rules do
    [
      {Dogma.Rules.FinalNewline},
      {Dogma.Rules.LineLength, max: 120, warn: 80}
    ]
  end
end
```

**Comment by lpil** [comment]
What does the line 

```elixir
{FinalNewline},
```

do in your example? Turn on that rule? Are all rules not in there disabled?

**Comment by meadsteve** [comment]
In my example only those two rules would be run. So the default config would probably contain all of the rules. It has the advantage of removing magic as everyone can see exactly what happens in what order. You can then also provide a couple of these config files if a few differing community standards arise.

**Comment by meadsteve** [comment]
Implementation-wise you could then just reduce over this list running: rule.test(). So it's not too different to the implementation you have now.

**Comment by lpil** [comment]
I think I'd rather have the config file explicitly turn rules off, rather than explicitly turn rules on.

I'm hugely influenced by rubocop, as you may be able to tell. :P

**Comment by meadsteve** [comment]
I'd spotted the rubocop influence :-) Ultimately it's your decision but I'm not really looking at this as a config file. I see it as a list of the rules that my repo is following. It's about making it explicit.

**Comment by lpil** [comment]
What happens when a new rule is introduced?

**Comment by meadsteve** [comment]
Well the default set would have to have the new rules added each time. For users with their own list they decide if they want the new rule and add them. This way you don't suddenly start failing rules you didn't expect to follow.

**Comment by lpil** [comment]
Perhaps. I think that would be acceptable for a minor version bump. I don't like the idea of people not knowing that new functionality exists though.

**Comment by meadsteve** [comment]
I agree. But I'd rather deal with that by encouraging people to use the default set. Which would get updated each time a rule is added.

**Comment by meadsteve** [comment]
@lpil so now that #42 is merged shall we consider this issue closed?

**Comment by lpil** [comment]
Yes, let's. Thanks Steve :)
