### ISSUE TITLE
How do we avoid mistaking string contents for Elixir code?

### ISSUE THREAD

**Issue by lpil** [lpil/dogma#52]
There are times were we cannot get enough information from the AST alone, in which case we need to inspect the source of the script itself.

When doing this, it's easy to mistake the contents of a string for code, resulting in false positives.

For example, if we wanted to ensure that the `+` operator always had a space around it, this code should not register any errors

```elixir
(String.graphemes("4+5") |> length) + 5
```

But unless we have a way of telling that it's in a string, we probably will probably get a false positive.

What about code in heredocs, or multi line strings?

```elixir
defmodule Foo do
  """
  defmodule Bar do
    Uh oh, what's going on here?
  end
  """
end
```

**Comment by meadsteve** [comment]
So all  the ast nodes have a line number right? I guess we could run over the nodes pairing them each with their line and then provide a function like ```Script.walk_with_text(fun)``` that takes a fun/3 with something like:
```elixir
def check_node(node, line_text, errors), do: ...
```

**Comment by meadsteve** [comment]
and maybe also the reverse that iterates over all lines but also provides any nodes generated by that line?

**Comment by lpil** [comment]
I'm not sure I follow, could you explain in more detail please?

My current thought was maybe trying to extract the Erlang tokeniser from the Elixir lang project.

**Comment by meadsteve** [comment]
I haven't fully thought this through myself yet. Might have to play around with some prototyping.

**Comment by meadsteve** [comment]
but given that each of the nodes looks something like this: ```{_, [line: line_number], _}``` it must be possible to figure out what context each line has.

**Comment by lpil** [comment]
For most expressions it's possible, but I don't know how you can identify whether it's a string or not on that line.

**Comment by lpil** [comment]
We've just stripped out all strings before processing.
