### ISSUE TITLE
Make sure we have a rule for everything on the elixir.community styleguide

### ISSUE THREAD

**Issue by meadsteve** [lpil/dogma#54]
http://elixir.community/styleguide has a number of points to follow. It'd be good if we could deal with everything on this.

**Comment by lpil** [comment]
Which ones are we missing?

**Comment by meadsteve** [comment]
Hopefully none. Just wanted to make sure so I thought I'd add an issue :smile:

**Comment by meadsteve** [comment]
In fact when you want to publicise this tool you could get them to dogma. Nice way of tying the community together.
