### ISSUE TITLE
Configuration proposal

### ISSUE THREAD

**Issue by lpil** [lpil/dogma#70]
### A draft for dogma configuration:

I think we should recommend you create a `config/dogma.exs` file, and load this file from your main config.exs.

Previous discussions with @meadsteve raised the question of whether the rules in the config file should be the only ones that are run, or whether the settings there override and add to the dogma default rule set.

Currently I'm leaning towards both! Specify a ruleset to start with (or explicitly set it to none), and then specify additional little configurations underneath. 

```elixir
config :dogma,

  # The ruleset to use. Defaults to `:all`
  # When set to nil no set will be used, and only get configuration from
  # `rule_config` will apply.
  rule_set: :all,

  # Additional configuration options that are used to change the behaviour of
  # your selected ruleset.
  # I see this as being the main way in which people configure Dogma for
  # their project- making a few tweaks here and there.
  
  rule_config: [
    TrailingWhitespace: false,
    LineLength: [length: 100],
    MyProject.MyCustomRule: true,
    # etc...
  ]
```

Are there better names for these keys? I'm not happy with `rule_config`. `overrides` ?

Ping @meadsteve, @richardbatty, and @jonnyarnold. It would be good to get your opinions!

**Comment by meadsteve** [comment]
I like the idea in general. I think this is a sensible way of managing the config.

One change I'd suggest though is breaking the rule config in to two pieces. It confused me a little that disabling rules and updating their config was handled in the same key. Maybe it would be better having a section of rules to skip and a section for config to override:
```elixir
  rule_set: :all,

  # Additional configuration options that are used to change the behaviour of
  # your selected ruleset.
  # I see this as being the main way in which people configure Dogma for
  # their project- making a few tweaks here and there.
  disabled_rules: [
    TrailingWhitespace
  ]

  # Not sure about the following. I wonder if additional rules should
  # always require a custom set.
  additional_rules: [
   MyProject.MyCustomRule
  ]

  rule_config_overrides: [
    LineLength: [length: 100]
  ]
```

**Comment by jonnyarnold** [comment]
Style checkers usually have a set of defaults:
- [JSHint](http://jshint.com/docs/) has a default, but [doesn't specifiy which ones are on by default](http://jshint.com/docs/options/).
- [Rubocop defines a default config file and loads it](https://github.com/bbatsov/rubocop/blob/master/config/default.yml), but provides you with options to override.
- [JSCS](http://jscs.info/overview.html) has everything off by default, but allows you to load [presets](http://jscs.info/overview.html#preset).

I think applications should always have sensible defaults, so I'd recommend specifying a default rule configuration and throwing up some kind of warning if Dogma doesn't find a config file.

Whilst I like @meadsteve's explicitness, I think it is obvious that "truthy means on and falsey means off" in @lpil's configuration. So I'd go for:

```elixir
config :dogma,
  rules: [
    TrailingWhitespace: false,
    LineLength: 100,
    MyProject.MyCustomRule: true,
    MyCustomRuleWithConfig: [
      first: 1,
      last: 2
    ]
  ]
```

**Comment by lpil** [comment]
We already have a concept of sets, which is (for me) an analogue of JSCS's styles (airbnb, google, etc), so we should specify them somehow.

If none is specified I want to default to a sane set.

**Comment by meadsteve** [comment]
@jonnyarnold my concern would be that it's not clear if flasey means "no config to override" or "disable rule". Both seem like at least partial valid meanings so without reading the docs/code I'm not sure someone knew to the project would understand what's intended. I always prefer explicitness in config files.

**Comment by jonnyarnold** [comment]
@meadsteve Can you explain what you mean by "no config to override"? In my head, there's only one way to interpret this:

*When I declare `RuleName: false` I do not want the declared rule to be run.*

**Comment by meadsteve** [comment]
@jonnyarnold from rereading your first message I think it may be some confusion around the sets. Currently the set gives a bundle of rules with some default configuration. So in @lpil 's example with 
```elixir
rule_set: :all
```
you get a load of rules with some default config (https://github.com/lpil/dogma/blob/master/lib/dogma/rules/sets/all.ex). So in that context if I later saw the list with a false value in it I would be unclear on what exactly this was doing.

However I spotted in your example that you didn't build on the set. So in that case it would make it a lot clearer.

**Comment by lpil** [comment]
This doesn't work.

```elixir
rule_config: [
  TrailingWhitespace: false,
]
```

That's not valid syntax.

```elixir
rule_config: [
  trailing_whitespace: false,
]
```
```elixir
rule_config: [
  {TrailingWhitespace: false},
]
```

```elixir
rule_config: %{
  TrailingWhitespace => false,
}
```

Or something else?

**Comment by meadsteve** [comment]
My vote would be for:
```elixir
rule_config: %{
  TrailingWhitespace => false,
}
```
simple and it keeps the key identical to the module name.

**Comment by jonnyarnold** [comment]
:+1:

**Comment by alxndr** [comment]
Here's another :+1: for the map-based syntax.

**Comment by lpil** [comment]
So I think I've done this now. Whey.
