### ISSUE TITLE
Run rules for a script in parallel 

### ISSUE THREAD

**Issue by lpil** [lpil/dogma#71]
If we do this, we probably want to make it so that rules return a list of errors, rather than the script with the errors attached so the errors can be concatenated and flattened easily.

http://www.theerlangelist.com/2015/07/beyond-taskasync.html

**Comment by meadsteve** [comment]
@lpil firstly: :+1: I like it. 
Secondly this probably won't be a huge amount of work to do with the Task module.  I can take a look at it this weekend if you want to assign it to me?

**Comment by lpil** [comment]
If you don't mind I quite wanted to do this myself, would be a good learning experience for me. :)

**Comment by meadsteve** [comment]
Not a problem at all :smile: it'd be a bit mean of me to steal all the fun bits whilst you're busy with a new job.

**Comment by lpil** [comment]
Doesn't seem to be a performance increase. See #72. Possibly doing something wrong.
