### ISSUE TITLE
Add a change log

### ISSUE THREAD

**Issue by meadsteve** [lpil/dogma#84]
Because http://keepachangelog.com/

**Comment by lpil** [comment]
After version 1.

**Comment by lpil** [comment]
https://github.com/olivierlacan/keep-a-changelog/blob/gh-pages/CHANGELOG.md

**Comment by alxndr** [comment]
FWIW change logs can be helpful before 1.0 as we

**Comment by lpil** [comment]
0.1 then? :D

**Comment by alxndr** [comment]
Sounds good to me!
