### ISSUE TITLE
LineLength Rule: customisable maximum length

### ISSUE THREAD

**Issue by lpil** [lpil/dogma#9]
Some heathens don't believe in sticking to 80 columns.

**Comment by meadsteve** [comment]
Would you consider warnings as well? Something that causes dogma to output but not fail? 
I've seen rules before that are warn at 80 fail at 120. Though I'm still not sure how I feel about this as nothing really stops you ignoring the warnings.

**Comment by lpil** [comment]
We could add a severity field to the error struct, and the formatters can decide how to present this information.

Personally I don't think this really adds anything.

**Comment by meadsteve** [comment]
also realised this is solved by PR #42. So we can close this too. Warnings we can come back to later. I've definitely gone off them.

**Comment by lpil** [comment]
Excellent.
